"""empty message

Revision ID: 566fd50c652b
Revises: 972a5d4dc222
Create Date: 2019-07-26 15:58:14.407791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566fd50c652b'
down_revision = '972a5d4dc222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selected',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selected')
    # ### end Alembic commands ###
