"""empty message

Revision ID: 98ddd4a603ca
Revises: e4f8ea0ff693
Create Date: 2019-07-26 17:12:51.325903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98ddd4a603ca'
down_revision = 'e4f8ea0ff693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('searched', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'searched')
    # ### end Alembic commands ###
