"""empty message

Revision ID: e4f8ea0ff693
Revises: 566fd50c652b
Create Date: 2019-07-26 16:06:54.998325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f8ea0ff693'
down_revision = '566fd50c652b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('selected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'selected')
    # ### end Alembic commands ###
